### ISSUE TITLE
Running bitwarden_rs-local-backup failed

### ISSUE THREAD

**Issue by houdini69** [shivpatel/bitwarden_rs-local-backup#1]
Firstly two remarks
- docker-compose-.yml is wrong at line 9 (need to remove one space)
- for accessing the container shell the first command is:
docker exec -it CONTAINER_ID /bin/bash
- For the decryption command, I got with
openssl enc -d -aes256 -salt -pbkdf2 -pass pass:_my_key_ -in /backups/db.sqlite_my_date_.tar.gz | tar xz -C /backups
bad decrypt
3069236568:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:583:
tar: invalid magic
tar: short read
What's wrong in my case?

**Comment by shivpatel** [comment]
@houdini69 thank you for pointing out the typos; they have been corrected now.

I tested the decryption command on my setup just now and everything worked fine. I tried again with the wrong encryption key and got an error similar to yours:

```
tar: invalid magic
tar: short read
error writing output file
```

Can you please ensure you are using the correct key to decrypt?

Please let me know so I can close this ticket when appropriate.

**Comment by houdini69** [comment]
Could you clarify if I have to put my key in plain text or the environment variable BACKUP_ENCRYPTION_KEY in the decryption command?
I got the error when putting my key (and  I put the correct one!)

**Comment by shivpatel** [comment]
@houdini69 plaintext in the command.

Here is the exact/working command I ran inside the container:
`openssl enc -d -aes256 -salt -pbkdf2 -pass pass:mykeygoeshere -in /backups/db.sqlite3_2021-01-01-180000.tar.gz | tar xz -C /backups`

**Comment by houdini69** [comment]
Thanks. I'll try as you explained.
